; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secrets.ini

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

; Connect secrets
;extra_configs = secrets.ini
build_flags =
    ${secrets.build_flags}
    -D VERSION=\"1.0.1\"

; Monitor settings
monitor_speed = 115200
upload_port = /dev/cu.usbserial-A5069RR4
upload_speed = 921600

; File system settings
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

; Libs autoload
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/NTPClient @ ^3.2.1
    adafruit/Adafruit BMP280 Library @ ^2.6.6
    adafruit/Adafruit Unified Sensor @ ^1.1.9


